horizons/gui/tabs/tabinterface.py
horizons/gui/tabs/tabwidget.py
horizons/gui/widgets/imagebutton.py
horizons/util/living.py

The game can be played longer, but still found 60+ icons or supported listeners not gced each selection.

fix some select memory leak bugs, partly resolve issue #2308

---

horizons/editor/gui.py
horizons/gui/tabs/inventorytab.py
horizons/gui/tabs/tabinterface.py
horizons/gui/tabs/tabwidget.py
tests/gui/helper.py

fix crash issue #2321 and #2315, and close mem-leak issue #2308

fix issue #2315 to prevent double hide of current_tab of TabWidget

---

horizons/gui/tabs/boatbuildertabs.py

How to reproduce:
1. Build barracks
2. Start building swordsmen
3. Start building another swordsmen
4. Crash due to missing swordsmen thumbnail for the que
This patch fixes this by using a fallback image. I kept the patch generic because we probably get more of these problems when we can produce different units.

Fix crash on missing thumbnails in unit queue

---

horizons/engine/generate_atlases.py
horizons/ext/polib.py
horizons/main.py
horizons/network/server.py
horizons/savegamemanager.py
horizons/util/savegameaccessor.py
horizons/util/yamlcache.py
horizons/util/yamlcachestorage.py
run_uh.py
setup.py
tests/game/test_load_save.py

Using the with-statement to open a file ensures it is closed even on
raised exceptions. Additionally, one cannot forget to call `.close()`.

Use contextmanager when opening a file

---

horizons/ai/aiplayer/__init__.py

Tow times import AbstractClayDeposit, in line 57 and 75.

remove double import AbstractClayDeposit

---

development/add_weblate_language.sh

Fixed add_weblate_language.sh that it works from development folder
Added command for create The_Unknown scenario po files
@MasterofJOKers please review it and when you want expand it

Some changes to: add_weblate_language.sh

---

horizons/engine/engine.py
horizons/gui/mousetools/selectiontool.py
horizons/gui/tabs/boatbuildertabs.py
horizons/messaging/queuingmessagebus.py

I change the code to make the running time faster.
Travis need for the code check now 49.242s to 49.900s. The other check need 61s to 69s.
I hope that it was not an (travis)exception, it can anyone confirm?

Avoid using `len(x)` to check if a list is empty

---

development/extract_strings_from_objects.py

add folder to sys.path

---

horizons/gui/modules/settings.py

Previous discussion: https://github.com/unknown-horizons/unknown-horizons/pull/2436

Made issue #2434 improvement

---

development/networkclient.py
horizons/ai/aiplayer/villagebuilder.py
horizons/component/componentholder.py
horizons/util/random_map.py
horizons/world/building/buildable.py
horizons/world/building/production.py
horizons/world/units/animal.py
run_server.py

Avoid unnecessary name repetition in equality comparisions

---

horizons/util/python/decorators.py

http://stackoverflow.com/questions/18171560/does-pep-require-whitespace-around-operators-in-function-arguments

add missing whitespace around arithmetic operator

---

content/gui/xml/ingame/widgets/captains_log.xml
horizons/gui/widgets/logbook.py

This pr fixes issue #2474 but it needs an scrollarena too but i dont know how to add them. I think something like here is needed: https://github.com/unknown-horizons/unknown-horizons/commit/a210d258729639598a5eb4bcb105ee306b9fa419

Fix issue: #2474

---

horizons/gui/modules/singleplayermenu.py
horizons/gui/widgets/minimap.py

I tried to do one of the points of #2515. Any thoughts?

No dummy in minimap

---

horizons/gui/modules/multiplayermenu.py
horizons/gui/modules/playerdataselection.py
horizons/network/networkinterface.py
horizons/util/color.py
horizons/util/startgameoptions.py
horizons/world/player.py
tests/game/__init__.py
tests/game/test_combat.py
tests/unittests/util/test_color.py

This can be reimplemented in a similar style, but without the magic.
Closes: #2518

Remove metaclass magic from Color

---

setup.cfg

https://github.com/unknown-horizons/unknown-horizons/pull/2532

ignore W503 codestyle check

---

content/packages/unknown-horizons.6

* Change bug tracker URL from http://bugs.unknown-horizons.org to https://github.com/unknown-horizons/unknown-horizons/issues
* Change date
* Remove redundant game name. Man pages don't usually repeat the name of the command in the description
> -\fBUnknown Horizons\fR: isometric 2D real-time strategy/simulation fun.
> +isometric 2D real-time strategy/simulation fun.

change man page

---

content/gui/xml/ingame/tabwidget/warehouse/buysellmenu.xml

Changed size from 225,80 to 225,70

Changed size of the text that was cut off

---

tests/gui/__init__.py

E713 test for membership should be 'not in'

E713 test for membership should be 'not in'

---

horizons/gui/tabs/tabwidget.py

About this discussion: https://github.com/unknown-horizons/unknown-horizons/pull/2591/files/079bfce1d3d4597595a3c16f2ec876bf5a82e41a#r94624448

rewrite check tabs

---

run_uh.py

Add missing gettext imports to run_uh.py

---

content/gui/xml/mainmenu/hotkeys.xml

Fixes broken label positions in hotkeys menu.

Fix layout for hotkeys menu

---

tests/utils.py

@MasterofJOKers could you review?

change to the `.format()` function

---

tests/game/__init__.py
tests/game/test_farm.py
tests/game/test_load_save.py
tests/game/utils.py
tests/gui/__init__.py
tests/gui/helper.py
tests/gui/ingame/test_boatbuilder.py
tests/gui/ingame/test_traderoute.py
tests/unittests/__init__.py

Change to the `.format()` function in some file in the tests/ direction.
@MasterofJOKers could you review?

Format style

---

content/gui/xml/ingame/buildmenu/buildtab.xml
horizons/gui/tabs/tabwidget.py

Fixes the position of tab-icons and the icons in the buildtab.

Fixes positions of tabs and buildtab

---

horizons/util/dbreader.py

at the line 44 was the lenght at 180 character, I split in 4 line for easy reading.

change line lenght

---

horizons/savegamemanager.py

Is base of the idea of @squiddy
#2621 (comment)

Simplify get_savegamename_from_filename

---

horizons/world/worldutils.py

I adjusted the conditions so that there are no trees placed on sand tiles.

closes #2542

---

README.md

a badge to show the versions in the requirements.txt
https://requires.io/github/MarkusHackspacher/unknown-horizons/requirements/
If the team sees it useful, as team can log on to the service and make a proper one.

Requirements Status

---

README.md

Reverts unknown-horizons/unknown-horizons#2653

Revert "Requirements Status"

---

horizons/main.py

The `_find_matching_map` function required some rebuilding, which I did.

I#2507 - fix custom scenarios command-line option

---

horizons/gui/tabs/barrackstabs.py
horizons/gui/tabs/boatbuildertabs.py
horizons/gui/widgets/resourceoverviewbar.py
setup.cfg

change to the .format() function
found because I look for E228 missing whitespace around modulo operator

change to the .format() function

---

horizons/component/coloroverlaycomponent.py
horizons/component/namedcomponent.py
horizons/engine/settings.py
horizons/gui/modules/editorstartmenu.py
horizons/gui/modules/ingame.py
horizons/gui/modules/multiplayermenu.py
horizons/gui/modules/settings.py
horizons/gui/mousetools/navigationtool.py
horizons/gui/widgets/playerssettlements.py
horizons/gui/widgets/playersships.py

Change to the .format() function.
I make not changes at:
https://github.com/unknown-horizons/unknown-horizons/blob/master/horizons/gui/widgets/messagewidget.py#L351-L356
I think the unicode is not need with python 3.

Formatchange

---

horizons/ai/aiplayer/mission/domestictrade.py
horizons/ai/aiplayer/mission/foundsettlement.py
horizons/ai/aiplayer/mission/internationaltrade.py
horizons/ai/aiplayer/mission/preparefoundationship.py
horizons/ai/aiplayer/mission/specialdomestictrade.py

split long line

---

development/compare_string_lengths_in_pos.py
setup.py

I rename variable name that have the same name as built-in function.

Rename built-in function

---

horizons/ai/aiplayer/strategy/strategymanager.py
horizons/entities.py
horizons/gui/widgets/messagewidget.py
horizons/scenario/scenarioeventhandler.py

the last commit of change to the .format() function.
Now are the % in some ext files, in unreachable code of print_db_data.py and in
horizons/ai/aiplayer/strategy/strategymanager.py, maybe someone have a idea to fix it:
db_result = db("SELECT m.rowid FROM %s m, ai_fleet_mission f WHERE f.owner_id = ? and m.rowid = f.rowid" % db_table, self.owner.worldid)

change to the .format() function.

---

tests/unittests/mp/test_server_statistics.py

I have remove unused import pytest from the last PR #2705 .

remove unused import

---

development/extract_strings_from_sqlite.py
horizons/ai/aiplayer/basicbuilder.py
horizons/ai/aiplayer/mission/__init__.py
horizons/ai/aiplayer/mission/specialdomestictrade.py
horizons/ai/aiplayer/trademanager.py
horizons/ai/aiplayer/villagebuilder.py
horizons/component/stancecomponent.py
horizons/gui/modules/playerdataselection.py
horizons/gui/tabs/tabwidget.py
horizons/gui/widgets/playersoverview.py
horizons/gui/widgets/playerssettlements.py
horizons/gui/widgets/playersships.py
horizons/gui/widgets/productionoverview.py
horizons/network/server.py
horizons/util/atlasloading.py
horizons/util/cmdlineoptions.py
horizons/world/diplomacy.py
horizons/world/player.py
horizons/world/production/producer.py
horizons/world/traderoute.py
horizons/world/units/animal.py
horizons/world/units/collectors/animalcollector.py
horizons/world/units/collectors/collector.py
horizons/world/units/groundunit.py
horizons/world/units/weaponholder.py
setup.cfg

Fix PEP8 E251 unexpected spaces around keyword / parameter equals.

Fix PEP8 E251 unexpected spaces around keyword / parameter equals

---

content/gui/xml/mainmenu/settings.xml
horizons/gui/modules/settings.py

This is an attempt to adjust mouse sensitivity setting range and format of the displayed value to make more sense to players.

Make mouse sensitivity settings human-readable

---

setup.cfg
tests/game/test_buildings.py

fix PEP8 W293 blank line contains whitespace.
And add W2 to the setup.cfg, for automatic tests.

fix PEP8 W293 blank line contains whitespace

---

tests/gui/menu/test_multiplayer.py
tests/unittests/mp/test_run_server.py

Use `is` or `is not` to compare with `None`
https://www.quantifiedcode.com/app/issue_class/3IY8CZ0v

Use `is` or `is not` to compare with `None`

---

horizons/constants.py
horizons/main.py
horizons/util/checkupdates.py
horizons/util/platform.py
tests/unittests/util/test_check_updates.py
tests/unittests/util/test_platform.py

Point update check to new file location and refactor

---

development/networkclient.py
horizons/world/production/producer.py
setup.cfg

PEP8 fix E111 indentation is not a multiple of four

PEP8 fix E111 indentation is not a multiple of four

---

horizons/gui/mousetools/buildingtool.py
horizons/scenario/scenarioeventhandler.py
horizons/world/building/buildable.py
horizons/world/building/settler.py
horizons/world/units/collectors/collector.py
setup.cfg

PEP8 fix E131 continuation line unaligned for hanging indent

PEP8 fix E131 continuation line unaligned for hanging indent

---

development/combat_ai/diplomacy_graphs.py
horizons/engine/settings.py
horizons/savegamemanager.py
horizons/world/disaster/blackdeathdisaster.py
horizons/world/disaster/buildinginfluencingdisaster.py
horizons/world/player.py
setup.cfg

PEP8 fix E211 whitespace before ‘(‘

PEP8 fix E211 whitespace before ‘(‘

---

doc/AUTHORS.md

I maintain and also playing this awesome game from 2014 for Slackware Linux.
Thank you all!!!

Added packager for Slackware Linux

---

content/gui/xml/ingame/tabwidget/selectmulti/overview_select_multi.xml
content/gui/xml/ingame/tabwidget/ships/overview_war_ship.xml
content/gui/xml/ingame/widgets/stancewidget.xml
horizons/gui/tabs/selectmultitab.py

Stance and stub for new ships

---

horizons/gui/modules/singleplayermenu.py
horizons/gui/widgets/minimap.py

iter_minimap_points now uses other existing methods
get_minimap_color added to decrease code duplication.
This is some cleanup that I originally wanted to include in PR #2786

refactor minimap code

---

horizons/world/traderoute.py

Some code cleanup upon ttoocs' PR #2764

remove crash when ship trades at warehouse

---

horizons/world/traderoute.py

The minimal number of changes to get things to work (as in, not crash. Not sure why there's parameters getting read/set that don't exist... but I just wanted to play the game)
TL:DR; I could play a game in singleplayer after this.

Ifixthings

---

.travis.yml

rename the _fife.so and _fifechan.so files.
The `prename ...` lines might be redundant now, but I'm not sure about that

fix fife import in travis

---

horizons/constants.py
horizons/world/building/nature.py

put fields in the OBJECTS layer

---

tests/gui/__init__.py

Was broken by the recent buildtab refactoring

Fix gui test setup

---

content/gui/xml/mainmenu/credits.xml
development/generate_credits.py

The generate credits script still had some python2-only stuff.
I changed that and ran the script to update the actual credits.

fixed and ran generate_credits script

---

horizons/constants.py
horizons/ext/polib.py
horizons/gui/tabs/buyselltab.py
horizons/gui/widgets/minimap.py
horizons/view.py

Change the style in the way isort and pycodestyle want.
This makes travis a little happier, and should help us to use travis in a more meaningful way.

Use style from guidelines

---

horizons/ai/aiplayer/behavior/diplomacysettings.py
horizons/component/selectablecomponent.py
horizons/component/stancecomponent.py
horizons/component/tradepostcomponent.py
horizons/engine/pychan_util.py
horizons/gui/widgets/minimap.py
horizons/gui/widgets/resourceoverviewbar.py
horizons/gui/widgets/tooltip.py
horizons/gui/widgets/unitoverview.py
horizons/network/networkinterface.py
horizons/network/packets/__init__.py
horizons/network/server.py
horizons/scenario/conditions.py
horizons/util/changelistener.py
horizons/util/pathfinding/pathfinding.py
horizons/util/python/callback.py
horizons/util/savegameaccessor.py
horizons/util/savegameupgrader.py
horizons/util/shapes/rect.py
horizons/util/startgameoptions.py
horizons/util/uhdbaccessor.py
horizons/util/yamlcache.py

after this commit are in the code:
40      E201 whitespace after '('
265     E202 whitespace before ')'
683     E203 whitespace before ':'
988

fix E201 whitespace after '('

---

horizons/editor/gui.py

Fixed the tile bug.  See #2839

Fixed the tile bug. See #2839

---

horizons/ai/aiplayer/personality/default.py
horizons/world/units/movingobject.py

Fixed a crash involving missing elements in the default personality. (and a minor pycodestyle fix that made it in apparently)

Fixing a crash

---

.isort.cfg

add the libraries to the config file

Fix Travis fail with isort

---

horizons/ext/polib.py
requirements.txt

update polib to version 1.1.0

---

horizons/extscheduler.py

This should fix #2898 
I have not been able to reproduce that problem, so I don't know for sure if this fixes it, but based on the backtrace this is what should fix it.

make sure that _ExtCallbackObject's always have an ordering

---

setup.cfg

#2918 Update codestyle to 2.5 check E117 Over-indented code blocks
Remove check E117 for TravisCI in setup.cfg

Not check E117 at codestyle check

---

horizons/extscheduler.py

SyntaxWarning: "is" with a literal.

---

content/packages/unknown-horizons.appdata.xml

See https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html basically what it does it advertise your game in Linux software centers more prominently. I also added https://hughsie.github.io/oars content rating metadata for parents.

Added an AppData.xml file 

---

development/all_images.py
development/combat_ai/diplomacy_graphs.py
development/compare_string_lengths_in_pos.py
development/compile_translation_win.py
development/docker/Dockerfile
development/docker/Singularity
development/docstringer.py
development/extract_strings_from_sqlite.py
development/extract_strings_from_xml.py
development/networkclient.py
development/print_db_data.py
development/print_profile_output.py
development/time_uh.py
development/translate_scenario.py
development/update_translations.py
horizons/ext/polib.py
requirements.txt
stage_build_mac.py
tests/gui/cooperative.py

https://wiki.debian.org/Python3-six-removal

remove dead Python2 code
