- horizons/gui/keylisteners/ingamekeylistener.py
Sometimes scrolling hangs when using the keyboard (especially when navigating fast).
How to reproduce:
1. Press and hold left arrow Key -> View moves to the left which is OK
2. Also press and hold right arrow key -> View still moves to the left which can be tolerated
3. Release left arrow key. -> View stops moving instead of moving right (as right arrow key is still pressed).
This patch resolves this issue.
> Fixed bug where keyboard scrolling hanged from time to time

- content/gui/xml/mainmenu/help.xml
- horizons/gui/modules/loadingscreen.py
#1821: Game play tips & help page scroll bar added
Longer description:
- As requested in #1821 game play tips for both categories (funny quotes and game play tips) are added.
- In the main menu of the game is a link to the help page where all game play tips are displayed. After adding tips, they floated below the logbook page. This was fixed by adding a scroll bar.
> #1821 gameplay tips and help page scrollbar

- .coveragerc
- .travis.yml
- README.md
Two things happen here. For one, we're collecting coverage data from gui
tests (support initially added in 563f8d4a).
Since we're running the unit/integrationtests at first to get early
feedback, we need to set a different COVERAGE_FILE in order to combine
the coverage data with the one from the gui tests.
Once everything's done, send the combined coverage data to coveralls.
> Enable code coverage tracking with coveralls

- horizons/gui/modules/singleplayermenu.py
- horizons/gui/widgets/minimap.py
In 6471ad0cf5be8c a hack was introduced to filter out the map data
written onto stdout from a subprocess. Sometimes more output is
generated by the subprocess, making it impossible to simply parse the
whole output as JSON.
While we could try to prevent any other output from happening (and
risking to break the map preview whenever some output leaks), or trying
to do something fancy (write into temporary files, pass a pipe.. does
that work windows?) ... at the end of the day, using stdout proved to be
working fine.
By moving some code around, and keeping serialization at the upmost
layer of the application, the communication and "protocol" is
selfcontained inside the singleplayermenu module.
Closes #2193
> Make hack for filtering out map preview data look nicer

- horizons/gui/widgets/routeconfig.py
- tests/gui/ingame/test_traderoute.py
Fixes #2525 
---
While this fixes the bug (and doesn't seem to break anything else), it isn't a proper solution really. Currently, I assume most widgets do not differentiate between beeing hidden and hiding them because the game is closing.
Then again, perhaps the route config is an outlier here, as it interacts with the GUI (message_widget) when it is beeing hidden.
> Fix crash when closing game while route config is open

- content/gui/xml/ingame/widgets/island_production.xml
- horizons/gui/util.py
- horizons/gui/widgets/productionoverview.py
> Fix space issues in production overview

- development/compare_string_lengths_in_pos.py
- horizons/gui/ingamegui.py
- horizons/gui/keylisteners/ingamekeylistener.py
- horizons/gui/modules/playerdataselection.py
- horizons/gui/tabs/buildtabs.py
- setup.cfg
If it ok to solve the Codestyle E701 - E704, I can make it, today.
This are the line to change:
```
horizons/gui/ingamegui.py:496:14: E702 multiple statements on one line (semicolon)
horizons/gui/modules/playerdataselection.py:66:30: E703 statement ends with a semicolon
horizons/gui/tabs/buildtabs.py:265:40: E703 statement ends with a semicolon
horizons/gui/keylisteners/ingamekeylistener.py:54:47: E703 statement ends with a semicolon
horizons/gui/keylisteners/ingamekeylistener.py:56:47: E703 statement ends with a semicolon
horizons/gui/keylisteners/ingamekeylistener.py:58:47: E703 statement ends with a semicolon
horizons/gui/keylisteners/ingamekeylistener.py:60:47: E703 statement ends with a semicolon
development/compare_string_lengths_in_pos.py:74:29: E701 multiple statements on one line …
```
> Codestyle multiple statements on one line

- run_uh.py
I briefly looked through run_uh.py and noticed a couple of things that could be cleaned up to make the code base easier to handle. After the final commit, the exit_with_error function can be simplified as no call in run_uh.py will actually satisfy: `title + "." == message`.
I know those changes aren't significant, but they will hopefully help in finding more severe issues in the long run :).
> Some minor fixes to run_uh.py

- run_uh.py
While trying to work out the TODO point in the `setup_fife()` function definition, I noticed that `import_fife()` and `find_fife()` require major adjustments. The main rationale was that `import_fife()` and `find_fife()` both return Boolean values and duplicate fife import calls. Below a brief rundown of introduced changes:
- `import_fife()` was renamed to `find_fife()`. The previous name was confusing, because the function originally only checked whether fife can be found in the provided 'paths'. Also, this is the only function that really checks whether fife exists in the specified paths. Alternatively, one could add an earlier return value when `find_fife()` finds the fife module. This can still be evaluated in if-else statements, as return None == False is true.
- `find_fife()` was …
> Major adjustments to import_fife, find_fife and setup_fife

- run_uh.py
Very minor fixes to the `exit_with_error()` function. Since the TODO later in the code was addressed, the `title + '.' != message` check is not needed anymore. In fact, it will never return True. At least within run_uh.py.
Next, I will help LinuxDonald with pychan :).
> Run uh fixes2

- horizons/gui/widgets/tooltip.py
Fix for ERROR: /home/travis/build/unknown-horizons/unknown-horizons/horizons/gui/widgets/tooltip.py Imports are incorrectly sorted.
> sort imports

- .travis.yml
With this line can travis do the work without error only if it started from unknown-horizons/unknown-horizons.
Other user get an error back.
> remove change directory

- run_uh.py
Replace the deprecated `imp` module with a workaround that temporarily modifies `sys.path`. This is a simpler solution than using `importlib` (replacement for `imp`) or third-party modules.
> 2667 imp to importlib

- horizons/gui/tabs/residentialtabs.py
Fixes crash when clicking on a tent.
> 
> Traceback (most recent call last):
>  File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
>     self.apply_select()
>  File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 151, in apply_select
>     next(iter(selected)).get_component(SelectableComponent).show_menu()
>  File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/component/selectablecomponent.py", line 100, in show_menu
>     self.session.ingame_gui.show_menu(tabwidget)
>  File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/ingamegui.py", line 311, in show_menu
>     self._old_menu.show()
>  File …
> Fix text formatting for inhabitants count/max

- horizons/gui/tabs/selectmultitab.py
```
Traceback (most recent call last):
File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 129, in mouseReleased
self.apply_select()
File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/mousetools/selectiontool.py", line 153, in apply_select
self.session.ingame_gui.show_multi_select_tab(selected)
File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/ingamegui.py", line 245, in show_multi_select_tab
tab = TabWidget(self, tabs=[SelectMultiTab(instances)], name='select_multi')
File "/disk/src/github/unknown-horizons/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 53, in __init__
self.current_tab.ensure_loaded() # loading current_tab widget
File …
```
> Fix crash when selecting multiple units

- horizons/gui/tabs/barrackstabs.py
- horizons/world/building/__init__.py
I added extra *hacks* for the smeltery and charcoal burner buildings. Now they are properly positioned. Although this resolves issue #1379, I feel our offset system is inherently broken and any semi-manual x , y adjustments barely compensate for that.
> Fix smeltery and charcoal_burning position offsets

- horizons/main.py
The travis-ci show this:
$ pycodestyle horizons tests *.py development
horizons/main.py:67:60: W291 trailing whitespace
horizons/main.py:599:1: W293 blank line contains whitespace
I change this.
> remove trailing whitespace

- horizons/gui/widgets/tooltip.py
When the tooltip would be partially off-screen it is now shown on the left side of the cursor
This is done by first calling show_tooltip (which will set the tooltips size) and then checking the size (instead of the other way around)
> Fix tooltip position when close to edge of screen (#2717)

- horizons/gui/widgets/tooltip.py
Because of bug #2776 buttons are often not clickable, but this can only occur when the tooltip and the button overlap.
This is a workaround for that problem by making sure that the tooltips for buttons are always below the button.
Horizontally the center of the tooltip is aligned with the center of the button, unless that would cause the tooltips to be off-screen,
The result is that for a given button its tooltip is always at the same location.
Also the cooldown for showing a tooltip has decreased.
It is very unlikely that a bug is not fixed by waiting 0.1 second for showing the same tooltip, but is fixed by waiting 1 second.
> Always show tooltips below buttons

- horizons/gui/widgets/minimap.py
- horizons/view.py
Since the map is isometric the minimap rotation was always (at least) 45 degrees off.
These changes solve that
Also, the minimap class has been majorly refactored, pulling most of the transformation code in its own class.
> show minimap with same rotation as map

- horizons/gui/keylisteners/ingamekeylistener.py
The `IngameKeyListener` seems to double fire `keyPressed` events.
The net effect is that it is impossible to use hotkeys such as 'B'
because the dropdown construction menu just flashes for an instant
and then closes back down immediately.
I suspect this is a deeper issue inside `fifengine`, but I am not
familiar with that so here I offer a quick fix to avoid the problem.
Simply put, the `IngameKeyListener` keeps track of the last event
and, if the current one is identical (same key, same press/release
status), it directly discards it without further processing.
Furthermore, I also cache an instance of `KeyConfig` inside
`IngameKeyListener` instead of instantiating one every time
`keyPressed` or `keyReleased` are called. This just popped to my eyes
as an obvious optimization to implement, …
> Avoid double-firing of `keyPressed` events

- horizons/gui/widgets/minimap.py
This was something I wanted to add to te previous pull request.
Without this, only a part of the map is shown if the use_rotation setting is off.
Now the corners of the minimap are shown as well in this situation.
> show minimap correctly without use_rotation

- content/settings-template.xml
The minimap looks better when rotated with the map, so it's better to enable that setting by default.
> Make MinimapRotation default to True

- horizons/gui/tabs/buyselltab.py
Somehow the buyselltab (trade from your own warehouse) did not have a tooltip.
This was probably because it set the helptext a bit differently than the other tabs.
This commit sets the helptext in the same way as the other tabs to fix the problem.
> show tooltip for buyselltab

- horizons/gui/tabs/buildtabs.py
- tests/gui/__init__.py
Also does some refactoring. `cur_build_menu_config` was a global variable that was supposed to keep track of this, but this task is actually done by the "BuildStyle" setting.
> make the build menu layout switch after clicking button once (fixes #2796)

- content/settings-template.xml
This solves the original problem of issue #2450 by also binding numpad plus and mins keys too speed up and speed down.
These bindings can not be seen or changed in settings menu.
This might be confusing for some players, but it seemed a general improvement anyways.
For some reason the key detector in the settings menu detects numpad plus as `PLUS` instead of `KP_PLUS`, making it impossible to bind the numpad keys from the settings.
Also, there are already two other bindings for speedup and the settings menu can only show 2 bindings.
This only sets the default, so if you already had a settings.xml this won't do anything.
You should delete your settings file (or copy-paste the changed lines from the template) for this to take effect.
> numpad plus and minus keys also set game speed.

- horizons/editor/gui.py
- horizons/gui/ingamegui.py
- horizons/gui/widgets/minimap.py
The rotation of the main view used to be stored in the savegame, but the minimap rotation would reset everytime a session is started,
Because of this the minimap could have a different rotation than the main view.
This update fixes that by making the minimap read the view rotation whenever a session is started or when the screen is rotated.
Also added some parameter documentation for MinimapTransform
> minimap rotation always matches main view rotation (fixes #2783)

- horizons/constants.py
- horizons/engine/generate_atlases.py
generate_atlases.py wasn't very consistent with usage of constants.
ATLAS_SOURCE_DIRECTORIES had the wrong directories.
This constant isn't used anywhere, so maybe it could even be removed altogether
> consistently use constants and os.path.join for atlases

- horizons/util/atlasloading.py
The poll loop will check and sleep when necessary.
No need to perform an extra sleep before.
> remove unnecessary sleep in startup

- content/gui/xml/ingame/tabwidget/warehouse/trade_single_slot.xml
- horizons/constants.py
- horizons/gui/tabs/buyselltab.py
- horizons/gui/widgets/routeconfig.py
Unfortunately it isn't possible to set multiple slots to the same resource (this would require large changes to TradePostComponent and TradeRoute), so 50 is the cap for automatically trading that resource
> capped items per trade slot at 50; fix/workaround for #1095

- horizons/util/loaders/sqliteanimationloader.py
- horizons/util/loaders/sqliteatlasloader.py
- horizons/world/building/__init__.py
- horizons/world/building/building.py
- horizons/world/ground.py
- horizons/world/units/__init__.py
Buildings are now drawn with as origin the center of their area (minus (0.5,0.5) to align with other parts of the code).
A y shift is used to position the image correctly (since the center of the image is almost always different than the center of the building).
This fixes #1379
The command passing for shifts if removed; the loaders are able to determine the proper shift themselves (based on image sizes)
Because the center is set as the origin, that is also the point for determining the z value of the building, and with that the ordering. This fixes #661
There are a few problems that remain:
- Buildings built on grass aren't aligned exactly with the grass. This is a problem from the grass sprites. (see #2807)
- For non-square buildings the ordering might be off sometimes. This is a result …
> change how buildings are placed and drawn

- horizons/gui/mousetools/attackingtool.py
- horizons/gui/mousetools/navigationtool.py
- horizons/gui/mousetools/pipettetool.py
- horizons/gui/mousetools/tearingtool.py
- horizons/gui/mousetools/tilelayingtool.py
All its subclasses as well.
This is done by setting it as a global listener.
This requires the latest git version of FIFE.
isConsumedByWidgets is used to check whether to fire or not.
This should solve problems #1413, #2778 and #2787.
This probably requires some playtesting.
It is likely that I missed some case where the mouseevent should not have fired through a widget.
> NavigationTool listens to mouseevents behind widgets

- horizons/gui/widgets/minimap.py
It might be possible now that the minimap is rotated incorrectly when starting the game.
Whenever the view rotates this is corrected again.
> fix #2819 by checking if view is None

- content/settings-template.xml
- horizons/gui/modules/hotkeys_settings.py
The listener for setting hotkeys used to use fifechan's keynames.
These don't completely match fife's keynames (for example for numpad keys)
This change makes the settings use the same listener that is used in game.
Also, this undoes #2792.
That PR was a workaround, but only gives trouble now the underlying problem is fixed.
> key settings use fife's listener instead of fifechan's (fix #2156)

- horizons/gui/keylisteners/mainlistener.py
replace check for attribute with check for none (the session class always has the ingame_gui attribute anyways)
> fix #2833: stop taking screenshot while loading from crashing game

- horizons/gui/widgets/minimap.py
- horizons/world/island.py
When a new settlement was made on a small map, not all pixels of the settlement would be coloured in the minimap.
This was because the minimap received a list of main map coordinates, but some main map coordinates correspond to multiple minimap coordinates. This means that some pixels in between are sometimes left empty.
Normal redrawing of the minimap draw all pixels. This update makes sure the minimap is redrawn when a settlement is placed.
The map editor probably has a similar problem that is not solved in this PR (because tile changes there are too common to redraw the minimap each time)
> redraw whole minimap when a settlement is placed

- horizons/world/building/settler.py
- tests/game/test_load_save.py
The test_settler_level_save_load test was supposed to test if a house upgrades correctly after saving and reloading the session.
It failed to take into account that there might not be enough inhabitants or that the inhabitants aren't happy enough.
This sets the taxes so that the inhabitants stay happy, and it makes sure that there are enought inhabitants.
The test still doesn't really make sense since there are 2 sessions: the one passed as argument and a newly created session. The building is placed in the argument session, and the waiting is there as well, while the save/load is done on the new session. I tried to fix this but that crashed it.
At least the test now makes a bit more sense.
> fix test_settler_level_save_load

- horizons/constants.py
- horizons/savegamemanager.py
- horizons/util/__init__.py
- horizons/util/migratepaths.py
- horizons/util/platform.py
- horizons/util/yamlcache.py
- tests/unittests/misc/test_paths.py
Unknown Horizons now puts user files in `$XDG_CONFIG_HOME/unknown-horizons`, `$XDG_DATA_HOME/unknown-horizons` and `$XDG_CACHE_HOME/unknown-horizons`.
For linux, the defaults are `~/.config/unknown-horizons`, `~/.local/share/unknown-horizons` and `~/.cache/unknown-horizons`.
For windows, the only difference is that the cache is placed in it's own directory (though it will also follow the XDG environment variables if they exist)
You can also override the paths using uh environment variables.
`$UH_USER_DIR` sets the directory for all user files. Data and config are both in this directory, and cache is in it's own subdirectory.
`$UH_USER_CONFIG_DIR`, `$UH_USER_DATA_DIR` and `$UH_USER_CACHE_DIR` can be used to set these directories indivually. These more specific options override …
> Follow XDG basedir specifications; fix #2749

- development/combat_ai/diplomacy_graphs.py
- development/networkclient.py
- development/print_db_data.py
- development/stringpreviewwidget.py
- development/translate_scenario.py
- development/update_translations.py
- tests/game/test_blackdeath.py
- tests/game/test_combat.py
- tests/game/test_fire.py
- tests/game/test_settlement_range.py
- tests/game/test_status_icons.py
After this PR are still existing cases:
pycodestyle horizons tests *.py development --select E20 --stat
163     E201 whitespace after '('
395     E202 whitespace before ')'
767     E203 whitespace before ':'
1325
> fix E201 whitespace after '('

- horizons/world/units/movingobject.py
Units have 2 different pathfinders.
One is the UH one in python, which deals with the long path, but only works in integer coordinates.
The other one is Fife's route system, which does the part between two paths on UH's pathfinder so the movement looks smooth.
For some unknown reason, Fife's route system is not always able to go where it is supposed to go and the ship will get stuck. It then tries to correct with absurd movements. See #2859.
This patch will make sure that the location of the fife instance is never too far from the actual location by checking the fife location whenever the actual location updates.
If the two locations are too far away from each other, the fife location will be set to the actual location.
This might result in a little jump now and then, but those are the …
> sync graphics location for moving objects

- CONTRIBUTING.md
github's flavor of markdown changed somewhat recently to forbid the space between the text and link
> Fix markdown links in contributing guidelines

- tests/dummy.py
All I did was:
1. create a python3.7 virtualenv
2. install a few dependencies and `pytest` in the virtualenv
3. `pytest tests --collect-only` (and fix the error)
> Fix test collection under python3.7

- horizons/util/platform.py
This creates config_dir, data_dir, and cache_dir if they do not exist.
This fixes errors like the following:
Warning: Unable to save cache into /home/clayton/.cache/unknown-horizons/yamldata.cache:
[Errno 2] No such file or directory
Also fixes #2865
> util/platform: create missing config, data, and/or cache dirs

- .travis.yml
Travis check:
python3.6
libfifechan0.1.4 is version 0.1.4+git20180904-1
python3-fife is version 0.4.1+git20180904-2
nongui tests:
======== 3 failed, 237 passed, 89 skipped, 2 xfailed in 156.24 seconds =========
gui:
============== 4 failed, 82 passed, 1 xfailed in 1015.90 seconds ===============
with old version:
============== 60 failed, 26 passed, 1 xfailed in 487.33 seconds ===============
It solve the Issues https://github.com/unknown-horizons/unknown-horizons/issues/2841
> travis check fife 0.4.1+git20180904-2

- horizons/util/__init__.py
- horizons/util/pathfinding/pathfinder.py
- tests/gui/conftest.py
- tests/unittests/misc/test_paths.py
Fix the path test that was broken in #2844
Replace deprecated access to pytest._Result.result and to collections.Container (pytest was warning about this).
> fixed test_paths and replaced deprecated code

- horizons/engine/generate_atlases.py
os.stat_float_times(False) was used to make sure that os.path.getmtime() would return integers.
However, this call has been deprecated since python 3.3, and removed since python 3.7
The result of this was that users of newer python versions aren't able to generate atlases.
All calls to os.path.getmtime(...) in the atlas generation program are changed int(os.path.getmtime(...)) so the actual behaviour doesn't change.
> Remove deprecated call to os.stat_float_times

- horizons/util/platform.py
When the paths for the game directories (data, config and cache) do not exist UH now does not only automatically create these directories themselves, but also their parent directories.
The drawback of this is that if some user misspelled one of the paths they probably won't notice it because UH will just make a directory with the misspelled path.
A second opinion on what is most desirable would be nice.
> Also create parent directories for game files

- setup.py
In setup.py it now also calls generate_atlases.py
I have not really tested this well.
It does seem to run, but I haven't yet tried it in the same environment that setup.py usually runs in.
> generate atlases during setup; should fix #2716

- horizons/engine/generate_atlases.py
- setup.py
horizons/engine/generate_atlases.py:66:1: E305 expected 2 blank lines after class or function definition, found 1
setup.py:236:1: E303 too many blank lines (4)
> solve pycodestyle

- horizons/constants.py
Some of the names (etc) use non-ASCII characters.
Let's use UTF-8 here.
> Use UTF-8 for constants.py

- run_uh.py
Most users won't stay in IRC long enough for us to see and answer their problems.
It is better to mention github issues and discord first so that will be the first place they'll go
> name github issues as first help channel

- requirements.txt
- setup.py
platform.dist()[0].lower() will be deprecated beginning with Python 3.7.
replace with distro.linux_distribution(full_distribution_name=False)[0]
> replace deprecated to distro package

- content/gui/xml/ingame/widgets/players_overview.xml
The original string in English shouldn't have a space before ":"
text: The total value from all individual entities or in short : Total Player Score
> removed space before ":"

- horizons/engine/generate_atlases.py
dont fail deleting files in `generate_atlases.py` if the files are already gone.
Without this patch, build on 1-core VMs sometimes failed with
```
intltool-merge -d po/uh/ content/packages/unknown-horizons.desktop.in build/share/applications/unknown-horizons.desktop
Merging translations into build/share/applications/unknown-horizons.desktop.
+ python3 horizons/engine/generate_atlases.py 2048
Traceback (most recent call last):
File "horizons/engine/generate_atlases.py", line 427, in <module>
AtlasGenerator.clear_everything()
File "horizons/engine/generate_atlases.py", line 407, in clear_everything
os.unlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/.cache/unknown-horizons/atlas-metadata.cache'
```
This PR was done while working on reproducible builds for …
> generate_atlases: dont fail deleting files

- horizons/util/loaders/actionsetloader.py
- horizons/util/loaders/loader.py
- horizons/util/loaders/tilesetloader.py
Sort input file lists
so that `actionsets.json` and `tilesets.json` build in a reproducible way
in spite of indeterministic filesystem readdir order
See https://reproducible-builds.org/ for why this is good.
This PR was done while working on reproducible builds for openSUSE.
> Sort input file lists

- horizons/util/checkupdates.py
Applied update check to release builds only, since comparing release and git version is unreliable in its current implementation.
The update checker currently compares the string "2019.1" (release) against "2019" (latest git version) and hence the git version is always treated as the older build and the wrong update notification popping up on each launch.
> Skip update check for development builds

- content/packages/unknown-horizons.appdata.xml
- run_uh.py
Here are 3 patches improving the flatpak support:
* (bytefix) Use https instead of http for the screenshot
* Add the latest release version in the appstream metadata
* Add the Flatpak prefix for the application
> Improve support for Flatpak

- horizons/util/loaders/jsondecoder.py
- horizons/util/preloader.py
* fix TypeError, see #2954
* The isAlive() function is deprecated and was change to is_alive().
>The isAlive() method of threading.Thread has been removed. It was deprecated since Python 3.8. Use is_alive() instead. (Contributed by Dong-hee Na in bpo-37804.)
https://docs.python.org/3.9/whatsnew/3.9.html#removed
> fixs for Phyton 3.9

- horizons/ai/aiplayer/combat/unitmanager.py
Compatibility fix for `Python 3.10` as per note below.
> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
> Rename instances of `collections.Iterable` into `collections.abc.Iterable`

- horizons/constants.py
- setup.py
This is makeshift, but probably enough to fix the build-blocking issue.
Fixes part of #2960 (as far as the version is concerned).
Converting the entire build to a modern architecture would still be recommended.
> Fix #2960: Generate PEP-440 compatible devbuild version for setuptools

- horizons/util/atlasloading.py
Game cannot be run on system with Pillow 10 installed because of unknown Image contant.
Image.ANTIALIAS was deprecated and removed from Pillow, now it uses only name LANCZOS which was used from Pillow version 5.0
> Python Pillow 10 compatibility
